version: '3'
services:

  traefik:
    image: 'traefik:v2.10.3'
    command:
      - '--log.level=DEBUG'
      - '--ping.entrypoint=web'
      - "--providers.file.directory=/config"
      - '--entrypoints.web.address=:8888'
      - '--accesslog=true'
      - '--providers.docker.network=linkdefendr_default'
    network_mode: host
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './config:/config'
    environment:
      - HOSTNAME

  database:
    image: "postgres:15.2-alpine"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
