spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
  flyway:
    validate-migration-naming: true

springdoc:
  swagger-ui:
    path: "/rest/swagger-ui"
  api-docs:
    path: "/rest/v3/api-docs"

logging:
  level:
    xyz.poeschl.urly: DEBUG
