spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
  flyway:
    validate-migration-naming: true
  mvc:
    servlet:
      path: "/rest"

springdoc:
  swagger-ui:
    path: "/swagger-ui"
